# Site settings
title: Sebastian Koochaki
email: Sebastian.koochaki@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "koochaki.github.io" # the base hostname & protocol for your site
github_username:  koochaki

# Build settings
markdown: kramdown
